export const ADD_CAREER = "ADD_CAREER";
export const RETRIEVE_CAREER = "RETRIEVE_CAREER";
export const LIST_CAREER = "LIST_CAREER";
export const UPDATE_CAREER = "UPDATE_CAREER";
export const DEACTIVATE_CAREER = "DEACTIVATE_CAREER";
export const ACTIVATE_CAREER = "ACTIVATE_CAREER";
export const APPLY_CAREER = "APPLY_CAREER";